/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore
// (it'll be regenerated by expo). It's included here so cold checkouts
// have it before the first `expo` run.
