name: Firebase

on:
  pull_request:
    paths:
      - "firebase/**"
      - ".github/workflows/firebase.yml"
  push:
    branches: [main]
    paths:
      - "firebase/**"
      - ".github/workflows/firebase.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci || npm install
      - run: npm run build
